/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.giacom.javaps3drum;

import java.awt.Component;
import java.net.URL;
import java.util.HashMap;

import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author sandrogiacom@gmail.com
 */
public class MainFrame extends javax.swing.JFrame {

	private static final long serialVersionUID = 7059587050547000452L;

	private HashMap<String, Component> componentMap;

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		try {
			UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
				| UnsupportedLookAndFeelException e) {
			e.printStackTrace();
		}

		initComponents();

		createComponentMap();

		this.setResizable(true);
		this.setLocationRelativeTo(null);
		this.setVisible(true);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jLabel_4 = new javax.swing.JLabel();
		jLabel_0 = new javax.swing.JLabel();
		jLabel_3 = new javax.swing.JLabel();
		jLabel_1 = new javax.swing.JLabel();
		jLabel_2 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jComboBox_controllers = new javax.swing.JComboBox();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(255, 255, 255));

		jLabel_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/4.png"))); // NOI18N
		jLabel_4.setName("jLabel_4"); // NOI18N

		jLabel_0.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/0.png"))); // NOI18N
		jLabel_0.setName("jLabel_0"); // NOI18N

		jLabel_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/3.png"))); // NOI18N
		jLabel_3.setName("jLabel_3"); // NOI18N

		jLabel_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
		jLabel_1.setName("jLabel_1"); // NOI18N

		jLabel_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/2.png"))); // NOI18N
		jLabel_2.setName("jLabel_2"); // NOI18N

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addGap(493, 493, 493)
										.addComponent(jLabel_3).addGap(2, 2, 2).addComponent(jLabel_0).addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
										jPanel1Layout.createSequentialGroup().addContainerGap().addComponent(jLabel_4)
												.addGap(250, 250, 250)))
						.addComponent(jLabel_1).addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(22, 22, 22).addComponent(jLabel_2)
								.addContainerGap(1435, Short.MAX_VALUE))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(jLabel_3).addComponent(jLabel_0))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jLabel_4)
						.addGap(0, 14, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(161, 161, 161).addComponent(jLabel_1)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel1Layout.createSequentialGroup().addGap(171, 171, 171).addComponent(jLabel_2)
								.addContainerGap(239, Short.MAX_VALUE))));

		jLabel_4.getAccessibleContext().setAccessibleName("jLabel_4");
		jLabel_0.getAccessibleContext().setAccessibleName("jLabel_0");
		jLabel_3.getAccessibleContext().setAccessibleName("jLabel_3");
		jLabel_1.getAccessibleContext().setAccessibleName("jLabel_1");

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		jComboBox_controllers.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jComboBox_controllersActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout
						.createSequentialGroup().addComponent(jComboBox_controllers,
								javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addContainerGap()
						.addComponent(jComboBox_controllers, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(160, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jComboBox_controllersActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox_controllersActionPerformed
		// When another controller is selected we have to remove old stuff.
	}// GEN-LAST:event_jComboBox_controllersActionPerformed

	public void showControllerDisconnected() {
		jComboBox_controllers.removeAllItems();
		jComboBox_controllers.addItem("Controller disconnected!");
	}

	public void setXYAxis(int xPercentage, int yPercentage) {
	}

	public void setControllerButtons(JPanel buttonsPanel) {
	}

	public void addControllerName(String controllerName) {
		jComboBox_controllers.addItem(controllerName);
	}

	public int getSelectedControllerName() {
		return jComboBox_controllers.getSelectedIndex();
	}

	public void setHatSwitch(float hatSwitchPosition) {

	}

	public void addAxisPanel(javax.swing.JPanel axesPanel) {
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox jComboBox_controllers;
	private javax.swing.JLabel jLabel_0;
	private javax.swing.JLabel jLabel_1;
	private javax.swing.JLabel jLabel_2;
	private javax.swing.JLabel jLabel_3;
	private javax.swing.JLabel jLabel_4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	// End of variables declaration//GEN-END:variables

	void changeImage(String buttonIndex, boolean pressed) {
		JLabel label = (JLabel) this.getComponentByName("jLabel_" + buttonIndex);
		String imageName;
		if (pressed) {
			imageName = buttonIndex + "p";
		} else {
			imageName = buttonIndex;
		}
		
		URL fileName = getClass().getResource("/images/" + imageName + ".png");

		System.out.println(fileName);

		try {

			label.setIcon(new javax.swing.ImageIcon(fileName));
			label.repaint();
			this.repaint();
		} catch (Exception e) {
		}

	}

	private void createComponentMap() {
		componentMap = new HashMap<>();
		Component[] components = jPanel1.getComponents();
		for (Component component : components) {
			System.out.println(component.getName());
			componentMap.put(component.getName(), component);
		}
	}

	public JComponent getComponentByName(String name) {
		if (componentMap.containsKey(name)) {
			return (JComponent) componentMap.get(name);
		} else
			return null;
	}
}
